### ISSUE TITLE
Linker Error

### ISSUE THREAD

**Issue by Nick177** [dan13ram/Graph#1]
Cause: include statement in main.cpp is causing errors to occur in the Graph implementation.
Change: A change from include "graph.cpp to include "graph.h" fixes the errors.

If you find this as a necessary change, I can send you a pull request of the changed version.

**Comment by dan13ram** [comment]
Hi, Can you please send me the pull request?
Thanks.

**Comment by dan13ram** [comment]
Hey. It had to be "graph.cpp" itself. 
I've implemented the Graph class in "graph.h" 
and its functions in the file "graph.cpp", where "graph.h" has been included in "graph.cpp".
Both these files are necessary for main.cpp to run. 

If you have problems running it, set the compiler options to run it with "-std=c++11".
Please check the updated README 
Thank you for your interest in my project :)
